window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\Tin\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_27076_DFMYBHRFTXSOPQNT",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-N2BPE8E",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\Tin",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Tin",
  "INIT_CWD": "C:\\wamp64\\www\\blog-newsletter",
  "INTEL_DEV_REDIST": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\Tin\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-N2BPE8E",
  "MIC_LD_LIBRARY_PATH": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\intel64_win_mic",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\Tin\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Tin\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Tin\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\Tin\\.npm-init.js",
  "npm_config_local_prefix": "C:\\wamp64\\www\\blog-newsletter",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Tin\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Tin\\.npmrc",
  "npm_config_user_agent": "npm/8.5.5 node/v16.15.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\wamp64\\www\\blog-newsletter\\package.json",
  "npm_package_name": "blog-newsletter",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Tin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "16",
  "OneDrive": "C:\\Users\\Tin\\OneDrive - Veleučilište u Virovitici",
  "OneDriveCommercial": "C:\\Users\\Tin\\OneDrive - Veleučilište u Virovitici",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\wamp64\\www\\blog-newsletter\\node_modules\\.bin;C:\\wamp64\\www\\node_modules\\.bin;C:\\wamp64\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\wamp64\\www\\blog-newsletter\\node_modules\\.bin;C:\\wamp64\\www\\node_modules\\.bin;C:\\wamp64\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;D:\\GPGGpg4win\\..\\GnuPG\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\Tin\\AppData\\Local\\Pub\\Cache\\bin;C:\\Users\\Tin\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Microsoft VS Code\\bin;C:\\Users\\Tin\\AppData\\Roaming\\npm;C:\\AndroidPlatformTools\\platform-tools;C:\\Flutter\\flutter\\bin;C:\\AndroidPlatformTools\\scrcpy;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\Tin\\.dotnet\\tools;C:\\Users\\Tin\\AppData\\Local\\GitHubDesktop\\bin",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "PROCESSOR_LEVEL": "25",
  "PROCESSOR_REVISION": "5000",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\Tin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\",
  "PUBLIC": "C:\\Users\\Public",
  "REACT_APP_APIKEY": "App 945c9bf931ea370b1d86d8e01ef4a302-b29943ca-b359-4fb3-b200-a94232ee495f",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\Tin\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.77.3",
  "TMP": "C:\\Users\\Tin\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-N2BPE8E",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-N2BPE8E",
  "USERNAME": "Tin",
  "USERPROFILE": "C:\\Users\\Tin",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-bf08eb11b2-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\Windows",
  "__PSLockDownPolicy": "0"
};